using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ISExam.Data.Entities
{
    public class Movie
    {
        //        Autogenerated PK Id, Name, Director,
        //Genre, Year, Rating, Box Office Earnings
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Director { get; set; }
        public string Genre { get; set; }
        public int Year { get; set; }
        public float Rating { get; set; }
        public float BoxOfficeEarnings { get; set; }
        public virtual IEnumerable<Client> Clients { get; set; } = new List<Client>();
    }
}
